---
scenario:
  name: with_ec2
driver:
  name: ec2
platforms:
  - name: prereqs1-centos7
    image: ami-9887c6e7
    region: us-east-1
    instance_type: t2.micro
    groups:
      - prereqsgroup
provisioner:
  name: ansible
  inventory:
    group_vars:
      prereqsgroup:
        dcos:
          selinux_mode: enforcing
  lint:
    name: ansible-lint
    enabled: False
lint:
  name: yamllint
  enabled: False
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: False
