---
- name: update all packages
  yum:
    name: "*"
    state: latest
    exclude: docker-ce,docker-engine,docker-engine-selinux
  when: os_system_updates

- name: install system utilities
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - tar
    - xz
    - unzip
    - curl
    - ipset
    - chrony
    - firewalld
    - dnsmasq
    - yum-utils
    - net-tools
    - bind-utils
    - bash
    - coreutils
    - gawk
    - gettext
    - grep
    - iproute
    - util-linux
    - sed

- name: disable selinux
  selinux: 
    policy: targeted
    state: permissive

- name: create group 'nogroup'
  group: 
    name: nogroup
    state: present

- name: ensure ipv6 is not disabled
  sysctl: 
    name: "{{ item }}"
    value: "0"
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: enable chronyd
  service:
    name: chronyd
    enabled: yes
    state: started

- name: disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: disable dnsmasq
  service:
    name: dnsmasq
    enabled: no
    state: stopped

- name: check if time is synchronized
  shell: "timedatectl status | grep 'NTP synchronized: yes'"
  register: timedatectl_result
  until: timedatectl_result.rc == 0
  changed_when: timedatectl_result.rc != 0
  retries: 5
  delay: 10